version: '3.6'

services:
  web:
    volumes:
      - "~/.composer/cache/:/home/.composer/cache/"
    environment:
      - TIKA_VERSION=1.24.1

      - PHP_IDE_CONFIG=serverName=$DDEV_SITENAME.ddev.site
      - XDEBUG_CONFIG=idekey=PHPSTORM

      # Env vars for auto setup of TYPO3
      ## See: https://docs.typo3.org/p/helhum/typo3-console/6.3/en-us/CommandReference/InstallSetup.html?highlight=typo3_install_db_driver#install-setup
      - TYPO3_CONTEXT=Development
      - TYPO3_INSTALL_WEB_SERVER_CONFIG=none
      - TYPO3_INSTALL_DB_DRIVER=mysqli
      - TYPO3_INSTALL_DB_USER=db
      - TYPO3_INSTALL_DB_PASSWORD=db
      - TYPO3_INSTALL_DB_HOST=db
      - TYPO3_INSTALL_DB_PORT=3306
      - TYPO3_INSTALL_DB_UNIX_SOCKET=
      - TYPO3_INSTALL_DB_USE_EXISTING=1
      - TYPO3_INSTALL_DB_DBNAME=db
      - TYPO3_INSTALL_ADMIN_USER=admin
      - TYPO3_INSTALL_ADMIN_PASSWORD=password
      - TYPO3_INSTALL_SITE_NAME=$DDEV_SITENAME (on DDEV)
      - TYPO3_INSTALL_SITE_SETUP_TYPE=no

      - TYPO3_HOST=${DDEV_SITENAME}.ddev.local

      # test environment for "standard EXT:Solr CI Build" for running inside of ddev web container
      - TYPO3_VERSION=^10.4
      - PHP_CS_FIXER_VERSION=2.16.1
      - TYPO3_DATABASE_HOST=db
      - TYPO3_DATABASE_NAME=db_tests
      - TYPO3_DATABASE_USERNAME=root
      - TYPO3_DATABASE_PASSWORD=root

      # test environment for nimut testing framework
      - typo3DatabaseName=db_tests
      - typo3DatabaseHost=db
      - typo3DatabaseUsername=root
      - typo3DatabasePassword=root
      - TESTING_SOLR_HOST=solr-tests
      - TESTING_SOLR_PORT=8985
    env_file:
      - ../.env
