version: '3.6'

services:
  solr:
    image: typo3solr/ext-solr:9.0.0
    restart: always
    ports:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983
  web:
    links:
      - solr:$DDEV_HOSTNAME
